apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: boinc
  name: boinc
spec:
  replicas: 3
  template:
    spec:
      $setElementOrder/containers:
      - name: boinc-client
      containers:
      - envFrom:
        - secretRef:
            name: boinc-united
        lifecycle:
          preStop:
            exec:
              command: ["/usr/bin/boinccmd", "--quit"]
        name: boinc-client
