apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: united
secretGenerator:
- name: boinc-united
  env: account.env
  type: Opaque
bases:
  - ../base
patchesStrategicMerge:
  - deployment.yaml
resources:
  - namespace.yaml
